# Generated by Django 5.0.2 on 2024-02-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg', models.IntegerField(primary_key=True, serialize=False)),
                ('college', models.CharField(default='vv college', max_length=50)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('phone', models.BigIntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('joing', models.DateTimeField()),
                ('dob', models.DateField()),
            ],
        ),
    ]
