# Generated by Django 5.0.2 on 2024-03-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=10)),
                ('brand_name', models.CharField(max_length=10)),
                ('colour', models.CharField(max_length=10)),
                ('length_width_height', models.CharField(max_length=25)),
                ('displacement', models.CharField(max_length=10)),
                ('power', models.CharField(max_length=30)),
                ('torque', models.CharField(max_length=30)),
                ('cylinder', models.CharField(max_length=2)),
                ('gear', models.CharField(max_length=10)),
                ('ground_clearance', models.CharField(max_length=10)),
                ('car_type', models.CharField(max_length=10)),
                ('engine', models.CharField(max_length=10)),
                ('fuel_tank', models.CharField(max_length=10)),
                ('prize', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
