# Generated by Django 5.0.2 on 2024-03-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0002_cardetails_delete_emp_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Date_of_birth', models.CharField(max_length=14)),
                ('Phone', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
