# Generated by Django 5.0.2 on 2024-03-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0004_registration_delete_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='id',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
