# Generated by Django 5.0.2 on 2024-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jango_app', '0005_remove_registration_id_alter_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='car_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
